---
name: standard-widgets
title:
  en: Standard Widgets
  fr: Widgets standards
description:
  en: Use these widgets for everyday widgeting
  fr: Ces widgets sont utilisables pour votre widgeting quotidien
authors:
  - baz
  - titi
  - Z
updated: 2013-03-15

